audit_header: false
title:
description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
show_custom_links: true
custom_links:
  - title: Location and Hours
    url: /location.html
  - title: Practice Areas
    url: /practice-areas.html
  - title: About
    url: /about.html
client:
  name: Richard A. Drews
  license_number:
  about_markdown: |

  market:
  brand:
  brokerage:
  address: 7018 North 102nd Circle<br>Omaha, NE 68122
  phone: 402-391-3712
  phone_type:
  phone2:
  phone2_type:
  email: rdrews98@gmail.com
  url:

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: /homevalue/
  second_CTA_text: Home Search
  second_CTA_URL: /homesearch/
  phone_CTA: true
  VR_form:

sidebar_CTA:
  CTA_image_path: /img/cta-images/004.jpg
  CTA_title: Set up a consultation
  CTA_text:
  CTA_link_text: Set up a consultation
  CTA_url:

welcome_box:
  welcome_headline:
  welcome_text_markdown:
socials:
  review_sm_icons: false
  facebook_url:
  linkedin_url:
  gplus_url:
  youtube_url:
  twitter_url:
  instagram_url:
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title:
  categories:
  image:
  subtitle:
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in -- MARKET --, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: '-- CLIENT NAME --'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 60rem
  hero_text: Richard A. Drews  |  Attorney at Law
  hero_background_hex: '#094264'
  hero_image_path: /img/background.jpg

site_colors:
  brand_color: '#2C3246'
  theme_color: '#2C3246'
  theme_text_color: '#353535'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 0px
  shadow_spread: 0px
  shadow_color: "#fff   "

buttons:
  button_radius_number: 0px
  button_padding_width_number: 10px
  button_padding_height_number: 15px
  button_border_color: '#ffffff'
  button_background_color: '#ffffff'
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
