title: Richard A Drews | Attorney at Law
description: 'Your Omaha Legal Expert'
show_custom_links: true
custom_links:
  - title: Location and Hours
    url: /location
  - title: Practice Areas
    url: /practice-areas
  - title: About
    url: /about
client:
  name: Richard A. Drews
  address: 7018 North 102nd Circle<br>Omaha, NE 68122
  phone: 402-391-3712
  email: rdrews98@gmail.com

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 60rem
  hero_text: Richard A. Drews  |  Attorney at Law
  hero_background_hex: '#eeeeee'
  hero_image_path: /img/home.jpg
  hero_image_path2: /img/location.jpg
  hero_image_path3: /img/practice.jpg
  hero_image_path4: /img/about.jpg
  hero_image_path5: /img/contact.jpg

site_colors:
  brand_color: '#2C3246'
  theme_color: '#2C3246'
  theme_text_color: '#353535'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 0px
  shadow_spread: 0px
  shadow_color: "#fff"

buttons:
  button_radius_number: 0px
  button_padding_width_number: 10px
  button_padding_height_number: 15px
  button_border_color: '#ffffff'
  button_background_color: '#ffffff'
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
